import { StyleSheet } from "react-native";
import { COLORS } from "../../../constants/Colors";
export default StyleSheet.create({
  container: {
    minHeight: "60%",
    paddingHorizontal: "4%",
  },
  postTitle: {
    fontSize: 19,
    fontWeight: "bold",
    marginTop: 10,
    backgroundColor: COLORS.WHITE,
    borderColor: COLORS.PAPASMURF300,
    height: 40,
    width: "100%",
    borderWidth: 1.5,
    borderRadius: 4,
    shadowOffset: { width: 1, height: 1 },
    shadowColor: COLORS.PAPASMURF300,
    shadowOpacity: 0.5,
    paddingLeft: 5,
  },
  postText: {
    fontSize: 18,
    marginTop: 10,
    backgroundColor: COLORS.WHITE,
    height: 300,
    width: "100%",
    borderRadius: 4,
    borderColor: COLORS.PAPASMURF300,
    borderWidth: 2,
    paddingBottom: 250,
    paddingLeft: 5,
  },
  text: {
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 17.6,
    marginTop: 20,
    color: COLORS.BLACK,
    textAlign: "left",
  },
  submitButton: {
    marginTop: 15,
    backgroundColor: COLORS.PAPASMURF500,
    paddingHorizontal: 25,
    paddingVertical: 14,
    borderRadius: 3,
    shadowOffset: { width: 1, height: 5 },
    shadowColor: COLORS.PAPASMURF300,
    shadowOpacity: 0.5,
    marginLeft: "auto",
  },
  submitText: {
    fontSize: 16,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  cancelButton: {
    backgroundColor: COLORS.RED_ERROR,
    paddingHorizontal: 25,
    paddingVertical: 14,
    borderRadius: 2,
    marginRight: 10,
  },
  buttonContainer: {
    flexDirection: "row",
    flexWrap: "nowrap",
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  modalView: {
    backgroundColor: COLORS.PAPASMURF100,
    borderRadius: 2,
    width: "100%",
    paddingVertical: 10,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    color: COLORS.OUTERSPACE500,
    fontWeight: "bold",
    width: "90%",
  },
  modalCancle: {
    color: COLORS.BLACK,
    fontSize: 12,
  },
  modalText: {
    fontSize: 14,
    color: COLORS.OUTERSPACE500,
  },
  closeModalText: {
    fontSize: 17,
    color: COLORS.OUTERSPACE500,
    textTransform: "uppercase",
    marginLeft: "auto",
  },
  modalHeader: {
    flexDirection: "row",
    flexWrap: "nowrap",
    width: "90%",
  },
  modalContainer: {
    width: "90%",
    paddingTop: 5,
    paddingBottom: 20,
  },
  customCloseButton: {
    marginLeft: "auto",
    alignSelf: "center",
    paddingRight: 12,
    fontSize: 20,
  },
  customCancleButton: {
    marginLeft: "auto",
    alignSelf: "center",
    right: 35,
    fontSize: 14,
  },
});
